kitapUygulama/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'arama/index'
  devise_for :users
  resources :kitaps, :path => "kitaplar" do
    resources :yorums
  end
  resources :yazars, :path => "yazarlar"
  root "kitaps#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

kitapUygulama/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

kitapUygulama/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

kitapUygulama/app/models/kitap.rb
class Kitap < ApplicationRecord
  has_many :yorums
  has_attached_file :resim, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :resim, content_type: /\Aimage\/.*\z/

  belongs_to :user
end

kitapUygulama/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :kitaps
end

kitapUygulama/app/models/yazar.rb
class Yazar < ApplicationRecord
end

kitapUygulama/app/models/yorum.rb
class Yorum < ApplicationRecord
  belongs_to :kitap
end

kitapUygulama/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale =params[:locale] || I18n.default_locale
  end
end

kitapUygulama/app/controllers/arama_controller.rb
class AramaController < ApplicationController
  def index
    @q=params[:q]
    @kitaplar=Kitap.where("isim=?",@q)
  end
end

kitapUygulama/app/controllers/kitaps_controller.rb
class KitapsController < ApplicationController
  before_action :set_kitap, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!, only: [:new]
   before_action :kontrol, only: [:edit, :destroy]
  # GET /kitaps
  # GET /kitaps.json
  def index
    @kitaps = Kitap.all
  end

  # GET /kitaps/1
  # GET /kitaps/1.json
  def show
  end

  # GET /kitaps/new
  def new
    @kitap = Kitap.new
  end

  # GET /kitaps/1/edit
  def edit
  end

  # POST /kitaps
  # POST /kitaps.json
  def create
    @kitap = Kitap.new(kitap_params)
    @kitap.user=current_user
    respond_to do |format|
      if @kitap.save
        format.html { redirect_to @kitap, notice: 'Kitap was successfully created.' }
        format.json { render :show, status: :created, location: @kitap }
      else
        format.html { render :new }
        format.json { render json: @kitap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitaps/1
  # PATCH/PUT /kitaps/1.json
  def update
    respond_to do |format|
      if @kitap.update(kitap_params)
        format.html { redirect_to @kitap, notice: 'Kitap was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitap }
      else
        format.html { render :edit }
        format.json { render json: @kitap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitaps/1
  # DELETE /kitaps/1.json
  def destroy
    @kitap.destroy
    respond_to do |format|
      format.html { redirect_to kitaps_url, notice: 'Kitap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitap
      @kitap = Kitap.find(params[:id])
    end
    def kontrol
      unless @kitap.user==current_user
        redirect_to kitaps_path, notice:"Yetki problemi" unless current_user==@kitap.user
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def kitap_params
      params.require(:kitap).permit(:isim, :sayfa, :resim)
    end
end

kitapUygulama/app/controllers/yazars_controller.rb
class YazarsController < ApplicationController
  before_action :set_yazar, only: [:show, :edit, :update, :destroy]

  # GET /yazars
  # GET /yazars.json
  def index
    @yazars = Yazar.all
  end

  # GET /yazars/1
  # GET /yazars/1.json
  def show
  end

  # GET /yazars/new
  def new
    @yazar = Yazar.new
  end

  # GET /yazars/1/edit
  def edit
  end

  # POST /yazars
  # POST /yazars.json
  def create
    @yazar = Yazar.new(yazar_params)

    respond_to do |format|
      if @yazar.save
        format.html { redirect_to @yazar, notice: 'Yazar was successfully created.' }
        format.json { render :show, status: :created, location: @yazar }
      else
        format.html { render :new }
        format.json { render json: @yazar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yazars/1
  # PATCH/PUT /yazars/1.json
  def update
    respond_to do |format|
      if @yazar.update(yazar_params)
        format.html { redirect_to @yazar, notice: 'Yazar was successfully updated.' }
        format.json { render :show, status: :ok, location: @yazar }
      else
        format.html { render :edit }
        format.json { render json: @yazar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yazars/1
  # DELETE /yazars/1.json
  def destroy
    @yazar.destroy
    respond_to do |format|
      format.html { redirect_to yazars_url, notice: 'Yazar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yazar
      @yazar = Yazar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yazar_params
      params.require(:yazar).permit(:isim)
    end
end

kitapUygulama/app/controllers/yorums_controller.rb
class YorumsController < ApplicationController
  def create
    @kitap = Kitap.find(params[:kitap_id])
    @yorum = @kitap.yorums.create(params[:yorum].permit(:isim, :mesaj))

    redirect_to kitaps_path(@kitap)
  end
end

kitapUygulama/app/helpers/application_helper.rb
module ApplicationHelper
end

kitapUygulama/app/helpers/arama_helper.rb
module AramaHelper
end

kitapUygulama/app/helpers/kitaps_helper.rb
module KitapsHelper
end

kitapUygulama/app/helpers/yazars_helper.rb
module YazarsHelper
end

kitapUygulama/app/helpers/yorums_helper.rb
module YorumsHelper
end

kitapUygulama/app/views/arama/index.html.erb
<h1>Arama#index</h1>
<%=@q%>
<br>
<table>
    <% @kitaplar.each do |kitap| %>
      <tr>
        <td><%= kitap.isim %></td>
        <td><%= kitap.sayfa %></td>
        <td><%= link_to 'Show', kitap %></td>
        <td> <%= image_tag kitap.resim.url(:thumb) if kitap.resim? %> </td>
        <td><%= link_to 'Edit', edit_kitap_path(kitap) %></td>
        <td><%= link_to 'Destroy', kitap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>
<p>Find me in app/views/arama/index.html.erb</p>

kitapUygulama/app/views/kitaps/_form.html.erb
<%= form_with(model: kitap, local: true) do |form| %>
  <% if kitap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kitap.errors.count, "error") %> prohibited this kitap from being saved:</h2>

      <ul>
      <% kitap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group has-success">
  <div class="field">
    <%= form.label :isim %>
    <%= form.text_field :isim, class:'form-control is-valid' %>
  </div>

  <div class="field">
    <%= form.label :sayfa %>
    <%= form.number_field :sayfa, class:'form-control is-valid' %>
  </div>

  <div class="field">
    <%= form.label :resim %>
    <%= form.file_field :resim%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

kitapUygulama/app/views/kitaps/edit.html.erb
<h1>Editing Kitap</h1>

<%= render 'form', kitap: @kitap %>

<%= link_to 'Show', @kitap %> |
<%= link_to 'Back', kitaps_path %>

kitapUygulama/app/views/kitaps/index.html.erb
<div class=" jumbotron lead">


<p id="notice"><%= notice %></p>

<h1><%= t 'kitaps'%></h1>
<%= t 'welcome'%>
<table class="table table-hover">

    <tr>
      <th class="table-dark"><%= t 'name' %></th>
      <th class="table-dark"><%= t 'page' %></th>
      <th class="table-dark" colspan="5"></th>
    </tr>

  <tbody>
    <% @kitaps.each do |kitap| %>
      <tr class="table-info">
        <td style='vertical-align:middle'><%= kitap.isim %></td>
        <td style='vertical-align:middle'><%= kitap.sayfa %></td>
        <td style='vertical-align:middle'><%= kitap.user.email %></td>
        <td style='vertical-align:middle'> <%= image_tag kitap.resim.url(:thumb) if kitap.resim? %> </td>
        <td style='vertical-align:middle'><%= link_to (I18n.t 'show'), kitap, :class => 'btn btn-primary', :style=> "text-decoration:none;" %> </td>
        <td style='vertical-align:middle'><%= link_to (I18n.t 'edit'), edit_kitap_path(kitap), :class => 'btn btn-warning', :style=> "text-decoration:none;" %></td>
        <td style='vertical-align:middle'><%= link_to (I18n.t 'destroy'), kitap, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger', :style=> "text-decoration:none;" %></td>
      </tr>
      <br>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to (I18n.t'new'), new_kitap_path, html_options = { :class=>"btn btn-success", :style=> "color:white; text-decoration:none;" } %>
</div>

kitapUygulama/app/views/kitaps/new.html.erb
<h1>New Kitap</h1>

<%= render 'form', kitap: @kitap %>

<%= link_to 'Back', kitaps_path, :class => 'btn btn-warning', :style =>'text-decoration:none;'%>

kitapUygulama/app/views/kitaps/show.html.erb
<div class=" jumbotron lead">
<p id="notice"><%= notice %></p>

<p>
  <strong>Isim:</strong>
  <%= @kitap.isim %>
</p>

<p>
  <strong>Sayfa:</strong>
  <%= @kitap.sayfa %>
</p>

<p>
  <strong>Resim:</strong>
  <%= image_tag @kitap.resim.url(:medium) if @kitap.resim? %>
</p>
<div class="comments">
  <h2> <%= @kitap.yorums.count %> Yorum </h2>
  <%= render @kitap.yorums %>

  <h3>Yorum Ekle</h3>
  <%= render "yorums/form" %>
</div>
<%= link_to 'Edit', edit_kitap_path(@kitap) , :class => 'btn btn-success', :style =>'text-decoration:none;'%> |
<%= link_to 'Back', kitaps_path, :class => 'btn btn-warning', :style =>'text-decoration:none;' %>
</div>

kitapUygulama/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KitapUygulama</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

kitapUygulama/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= image_tag('logo.png', size: "80x80") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="btn btn-success" style="text-decoration:none;" href="<%= kitaps_path %>"><%= t 'home'%> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="btn btn-success" style="text-decoration:none;"href="#"><%= t 'about'%></a>
      </li>
    </ul>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Giriş yaptı :<strong><%= current_user.email %></strong>.
      <%= link_to 'Profili Düzenle', edit_user_registration_path, :class => 'btn btn-success', :style=> "text-decoration:none;" %> |&nbsp;
      <%= link_to "Çıkış", destroy_user_session_path, method: :delete, :class => 'btn btn-success', :style=> "text-decoration:none;"  %>
    <% else %>
      <%= link_to (I18n.t 'signup'), new_user_registration_path, :class => 'btn btn-success', :style=> "text-decoration:none;"  %> |&nbsp;
      <%= link_to (I18n.t 'login'), new_user_session_path, :class => 'btn btn-success', :style=> "text-decoration:none;"  %>
    <% end %>
    </p>&nbsp;
    <p><%= link_to "En",{:locale => "en"}, :class => 'btn btn-success', :style=> "text-decoration:none;" %>&nbsp;
    <%= link_to "Tr",{:locale => "tr"}, :class => 'btn btn-success', :style=> "text-decoration:none;" %></p>


  </div>
</nav>

kitapUygulama/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

kitapUygulama/app/views/yazars/_form.html.erb
<%= form_with(model: yazar, local: true) do |form| %>
  <% if yazar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(yazar.errors.count, "error") %> prohibited this yazar from being saved:</h2>

      <ul>
      <% yazar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isim %>
    <%= form.text_field :isim %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

kitapUygulama/app/views/yazars/edit.html.erb
<h1>Editing Yazar</h1>

<%= render 'form', yazar: @yazar %>

<%= link_to 'Show', @yazar %> |
<%= link_to 'Back', yazars_path %>

kitapUygulama/app/views/yazars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Yazars</h1>

<table>
  <thead>
    <tr>
      <th>Isim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yazars.each do |yazar| %>
      <tr>
        <td><%= yazar.isim %></td>
        <td><%= link_to 'Show', yazar %></td>
        <td><%= link_to 'Edit', edit_yazar_path(yazar) %></td>
        <td><%= link_to 'Destroy', yazar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yazar', new_yazar_path %>

kitapUygulama/app/views/yazars/new.html.erb
<h1>New Yazar</h1>

<%= render 'form', yazar: @yazar %>

<%= link_to 'Back', yazars_path %>

kitapUygulama/app/views/yazars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isim:</strong>
  <%= @yazar.isim %>
</p>

<%= link_to 'Edit', edit_yazar_path(@yazar) %> |
<%= link_to 'Back', yazars_path %>

kitapUygulama/app/views/yorums/_form.html.erb
 <%= form_for([@kitap, @kitap.yorums.build]) do |f| %>
 <table class="table table-hover">
   <tr class="table-secondary">
     <td>  <p>
         <%= f.label :isim %>
         <%= f.text_field :isim %>
       </p>
     </td>
     </tr>
     <tr class="table-secondary">
     <td>
       <p>
       <%= f.label :mesaj %>
       <%= f.text_field :mesaj %>
     </p>
   </td>
   </tr>
   <tr class="table-secondary">
     <td>
       <p>
         <%= f.submit %>
       </p>
     </td>
   </tr>
</table>
<% end %>

kitapUygulama/app/views/yorums/_yorum.html.erb
<table class="table table-hover">


<div class="comment clearfix">
  <div class="comment_content">
    <tr class="table-light">
      <td>  <p class="comment_name"> <%= yorum.isim %> </p></td>
    </tr>
    <tr class="table-light">
      <td>    <p class="comment_time"> <%= yorum.mesaj %> </p></td>
    </tr>
    <tr class="table-light">
      <td>  <p class="comment_body"> <%= time_ago_in_words(yorum.created_at) %> Ago. </p></td>
    </tr>



  </div>

</div>
</table>